workspace:
  base: /go
  path: src/github.com/josmo/drone-elastic-beanstalk
pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  latest:
    image: plugins/docker
    username: josmo
    password: ${DOCKER_PASSWORD}
    repo: peloton/drone-elastic-beanstalk
    tag:
      - latest
      - ${DRONE_BUILD_NUMBER}
    when:
      branch: master
      event: push

plugin:
  name: Elastic Beanstalk
  desc: Deploy or update a project on AWS Elastic Beanstalk
  type: deploy
  image: plugins/drone-elastic-beanstalk
  labels:
    - aws
    - paas
