workspace:
  base: /go

pipeline:
    build:
      image: golang:1.6
      commands:
        - CGO_ENABLED=0 go build -ldflags "-s -w -X main.version=${DRONE_BUILD_NUMBER}"
    docker:
      username: ${DOCKER_USER}
      password: ${DOCKER_PASS}
      email: ${DOCKER_EMAIL}
      repo: plugins/drone-elastic-beanstalk
      tag: latest
      when:
        branch: master
        event: push

plugin:
  name: Elastic Beanstalk
  desc: Deploy or update a project on AWS Elastic Beanstalk
  type: deploy
  image: plugins/drone-elastic-beanstalk
  labels:
    - aws
    - paas
